services:
  web:
    container_name: compromise-web
    build: 
      context: ./compromise-react-web
      args:
        VITE_MODE: ${VITE_MODE}

    expose:
      - "80"
    networks:
      - bipsqwake-network
  api:
    container_name: compromise-ws
    build:
      context: ./compromise-ws
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_API_PROFILES_ACTIVE}
    expose:
      - "8081"
    networks:
      - bipsqwake-network
networks:
  bipsqwake-network:
    external: true
    