name: compromise-ws
server:
  port: 8081
# logging:
#   level:
#     root: DEBUG
appconfig:
  clean-period: 120000
  allowed-origins-pattern: "http://localhost:3000"
  allowed-methods: GET, POST, OPTIONS, DELETE
