name: compromise-ws
spring:
  application:
    name: compromise-ws
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# logging:
#   level:
#     root: DEBUG
appconfig:
  clean-period: 120000
  allowed-origins-pattern: "http://localhost:3000"
  allowed-methods: GET, POST, OPTIONS, DELETE
resilience4j.ratelimiter:
  instances:
    teseraLimiter:
      limit-for-period: 10
      limit-refresh-period: 1s
      timeout-duration: 5s
