name: compromise-ws
spring:
  application:
    name: compromise-ws
server:
  port: 8081
# logging:
#   level:
#     root: DEBUG
external:
  kinopoisk: "https://api.kinopoisk.dev/v1.4/"
  kinopoiskKey: ${KP_KEY}
  bgg: "https://boardgamegeek.com/xmlapi2"
  tesera: "https://api.tesera.ru/v1/" 
appconfig:
  clean-period: 120000
  allowed-origins-pattern: "http://localhost:3000"
  allowed-methods: GET, POST, OPTIONS, DELETE
resilience4j.ratelimiter:
  instances:
    teseraLimiter:
      limit-for-period: 10
      limit-refresh-period: 1s
      timeout-duration: 5s
