# logging:
#   level:
#     root: DEBUG
appconfig:
  allowed-origins-pattern: "https://synkro.bipsqwake.ru"
eureka:
  client:
    service-url:
      defaultZone: http://compromise-discovery:8761/eureka/