# logging:
#   level:
#     root: DEBUG
appconfig:
  allowed-origins-pattern: "http://192.168.0.35:3000"
external:
  kinopoisk: "https://api.kinopoisk.dev/v1.4/"
  kinopoiskKey: ${KP_KEY}
  bgg: "https://boardgamegeek.com/xmlapi2"
  tesera: "https://api.tesera.ru/v1/" 